queue_rules:
  - name: default
    conditions: []
pull_request_rules:
  - name: Check ci success
    conditions:
      - check-success=CI/Jenkins/twister
      - or:
        - check-success=CI/Jenkins/integration
        - check-neutral=CI/Jenkins/integration
    actions:
      label:
        add:
          - ci-passed
  - name: Check ci missing
    conditions:
      - check-success!=CI/Jenkins/twister
    actions:
      label:
        remove:
          - ci-passed
  - name: merg using default queue
    conditions:
      - base=main
      - label!=urgent
      - "#approved-reviews-by>=1"
      - check-success=CI/Jenkins/twister
      - or:
        - check-success=CI/Jenkins/integration
        - check-neutral=CI/Jenkins/integration
    actions:
      queue:
        name: default
        method: rebase
  - name: No approvals needed
    conditions:
      - base=v-1.7
      - label!=urgent
      - "#approved-reviews-by>=0"
      - title~=^\[backport\].*
      - check-success=CI/Jenkins/twister
      - or:
        - check-success=CI/Jenkins/integration
        - check-neutral=CI/Jenkins/integration
    actions:
      queue:
        name: default
        method: rebase

