queue_rules:
  - name: default
    conditions: []
pull_request_rules:
  - name: Check ci status
    conditions:
      - check-success=CI/Jenkins/twister
      - or:
        - check-success=CI/Jenkins/integration
        - check-success=CI/Jenkins/integration-skipped
    actions:
      label:
        add:
          - ci-check-success
  - name: merg using default queue
    conditions:
      - base=main
      - label!=urgent
      - "#approved-reviews-by>=1"
      - check-success=CI/Jenkins/twister
      - or:
        - check-success=CI/Jenkins/integration
        - check-success=CI/Jenkins/integration-skipped
    actions:
      queue:
        name: default
        method: rebase
  - name: No approvals needed
    conditions:
      - base=main
      - label!=urgent
      - "#approved-reviews-by>=0"
      - title~=^[backport].*
      - check-success=CI/Jenkins/twister
      - or:
        - check-success=CI/Jenkins/integration
        - check-success=CI/Jenkins/integration-skipped
    actions:
      queue:
        name: default
        method: rebase
 
