name: Code Review

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types:
      - review_requested

jobs:
  review_full:
    if: github.event.action == 'review_requested' && github.event.requested_reviewer.login == 'Nordicbuilder'
    runs-on: ubuntu-latest
    steps:
      - name: Full PR Diff Review
        uses: NordicBuilder/ChatGPT-CodeReview@takeAllCommits
        env:
          GITHUB_TOKEN: ${{ secrets.NORDICBUILDER_GPT }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          # PROMPT: "Please review the entire pull request diff as it stands now. Be concise, and report any confusions or irregularities you observe."
          IGNORE_PATTERNS: /dummy_modules/**/*,dummy.md
          INCLUDE_PATTERNS: "*.*"
