name: Code Review

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types:
      - review_requested

jobs:
  review_full:
    if: github.event.action == 'review_requested' && github.event.requested_reviewer.login == 'Nordicbuilder'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          repository: NordicBuilder/action-ai-reviewer
          ref: takeAllCommits
          token: ${{ secrets.NORDICBUILDER_GPT }}
          path: ./.github/actions/action-ai-reviewer
      - name: Full PR Diff Review
        uses: ./.github/actions/action-ai-reviewer/
        env:
          GITHUB_TOKEN: ${{ secrets.NORDICBUILDER_GPT }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          IGNORE_PATTERNS: /placeholder
          INCLUDE_PATTERNS: "*.*"
