name: Code Review

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types:
      # - opened
      # - synchronize
      # - reopened
      - review_requested

jobs:
  review_full:
    if: github.event.action == 'review_requested' && github.event.requested_reviewer.login == 'Nordicbuilder'
    runs-on: ubuntu-latest
    steps:
      - name: Full PR Diff Review
        uses: NordicBuilder/ChatGPT-CodeReview@takeAllCommits
        env:
          GITHUB_TOKEN: ${{ secrets.NORDICBUILDER_GPT }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          # This prompt instructs to review the entire PR diff.
          # PROMPT: "Please review the entire pull request diff as it stands now. Be concise, and report any confusions or irregularities you observe."
          # PROMPT: "Take a deep breath and review all commits in this PR. Be concise, and report any confusions or irregularities you observe."
          # PROMPT: "Do not print text other than you need to avoid exceeding your token limits. Review all commits in this PR. I only need final answer."
          # PROMPT: "DO NOT PROVIDE ANY OTHER TEXT THAT THE PYTHON CODE. NOT IN FRONT OF CODE AND NOT AFTER THE CODE!"
          # PROMPT: "Sanity check user question. If there are typos, fix them. If there are related items that user may have meant, provide all that information instead.""
          # LANGUAGE: English
          # OPENAI_API_ENDPOINT: https://api.openai.com/v1 #Default 
          # MODEL: gpt-4o-mini
          # top_p: 1 #An alternative to sampling with temperature. 0.1 means only the tokens comprising the top 10% probability mass are considered.
          # temperature: 1 #What sampling temperature to use, between 0 and 2. Higher values like 0.8 will make the output more random, while lower values like 0.2 will make it more focused and deterministic
          # max_tokens: 10000
          # MAX_PATCH_LENGTH: 10000
          IGNORE_PATTERNS: /dummy_modules/**/*,dummy.md
          INCLUDE_PATTERNS: "*.*"

  # review_incremental:
  #   if: github.event.action != 'review_requested' && contains(github.event.pull_request.requested_reviewers.*.login, 'Nordicbuilder') #add comments only to diff
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Incremental Commit Review
  #       uses: NordicBuilder/ChatGPT-CodeReview@main
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.NORDICBUILDER_GPT }}
  #         OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  #         # This prompt instructs to review only the changes in the latest commit.
  #         PROMPT: "Please review the changes introduced in the latest commit. Be concise and comment only on any confusions or irregularities."
  #         LANGUAGE: English
  #         OPENAI_API_ENDPOINT: https://api.openai.com/v1
  #         MODEL: gpt-4o-mini
  #         top_p: 1
  #         temperature: 1
  #         max_tokens: 10000
  #         MAX_PATCH_LENGTH: 10000
  #         IGNORE_PATTERNS: /dummy_modules/**/*,dummy.md
  #         INCLUDE_PATTERNS: "*.*"
