name: List GitHub accounts

on:
  push:
    branches:
      - list_accounts

# on:
#   schedule:
#     - cron: '40 4 * * *'

jobs:
  list-accounts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        with:
          path: nrf
          fetch-depth: 0

      - name: Install script dependencies
        working-directory: nrf
        run: |
          pip3 install -r doc/_scripts/list_accounts/requirements.txt

      - name: Create list
        run: |
          mkdir ids

          declare -a names=("mcuboot" "matter" "homekit")
          declare -a repos=("nrfconnect/sdk-mcuboot" "nrfconnect/sdk-connectedhomeip" "nrfconnect/sdk-homekit")
          length=${#names[@]}

          for i in `seq $length`; do
            name=${names[$i-1]}
            repo=${repos[$i-1]}

            python3 nrf/doc/_scripts/list_accounts/list_accounts.py \
              --token "${{ secrets.NCS_GITHUB_TOKEN }}" \
              --repository "$repo" \
              --output-file "ids_${name}.txt"

            touch ids/github_${name}_users.pwd
            for id in $(cat ids_${name}.txt); do
              htpasswd -b ids/github_${name}_users.pwd $id ${{ secrets.DOC_ID_PASSWORD }}
            done
          done

      - name: Install azcopy
        run: |
          sudo apt update
          wget -P azcopy/bin https://azcopyvnext.azureedge.net/release20221108/azcopy_linux_amd64_10.16.2.tar.gz
          cd azcopy/bin && tar --strip-components=1 -xzf azcopy_linux_amd64_10.16.2.tar.gz
          echo "${PWD}/azcopy/bin >> $GITHUB_PATH"
          azcopy -v
      
      - name: AzCopy login
        env:
          AZCOPY_SPA_APPLICATION_ID: ${{ secrets.AZCOPY_SPA_APPLICATION_ID }}
          AZCOPY_SPA_TENANT_ID: ${{ secrets.AZCOPY_SPA_TENANT_ID }}
          AZCOPY_SPA_CLIENT_SECRET: ${{ secrets.AZCOPY_SPA_CLIENT_SECRET }}
        run: azcopy login --service-principal --application-id ${AZCOPY_SPA_APPLICATION_ID} --tenant-id ${AZCOPY_SPA_TENANT_ID}

      - name: Upload ID files
        run: |
          export AZCOPY_CONCURRENCY_VALUE="AUTO"
          azcopy copy "ids/*" "https://ncsdocsa.blob.core.windows.net/ncs-doc-authorization/" --from-to=LocalBlob --overwrite=true --put-md5 --recursive --log-level=WARNING
