name: Zip and Send
on:
  push:
    branches:
      - zipAndSend

jobs:
  zip-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Checkout sources
        uses: nordicbuilder/action-checkout-west-update@main
        with:
          git-fetch-depth: 0
          path: workspace/nrf

      - name: Create tar
        run: >
          tar -C ./workspace -cvf src.tar.gz .

      - name: Configure and Upload to Artifactory
        env:
          ARTIFACTORY_URL: https://eu.files.nordicsemi.com/artifactory
          REPOSITORY: ncs-src-mirror
          FILE_PATH: src.tar.gz
          TARGET_PATH: __${{ github.ref_name }}/
        run: >
          jfrog rt c add --interactive=false --url=$ARTIFACTORY_URL
          --user=${{ secrets.COM_NORDICSEMI_FILES_USERNAME }}
          --password=${{ secrets.COM_NORDICSEMI_FILES_PASSWORD }} &&
          jfrog rt u $FILE_PATH $REPOSITORY/$TARGET_PATH
