name: Zip and Send
# on:
#   push:
#     tags:
#       - '*'

on:
  push:
    branches:
      - zipAndSend

jobs:
  zip-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: 'recursive'

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install West
        run: pip install west

      - name: Initialize West Workspace
        run: |
          west init -l .
          west update

      - name: Zip repository
        run: zip -r sdk-repository-${{ github.sha }}.zip . -x "*.git*"

      - name: Upload ZIP as artifact
        uses: actions/upload-artifact@v2
        with:
          name: sdk-repository-zip
          path: sdk-repository-${{ github.sha }}.zip
