name: Zip and Send
on:
  push:
    branches:
      - zipAndSend

jobs:
  zip-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          path: sdk-nrf
          fetch-depth: 0
          submodules: 'recursive'

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install West
        run: pip install west

      - name: Initialize West
        run: |
          cd sdk-nrf
          west init -l .

      # - name: West update
      #   run: west update

      - name: Create tar.gz
        run: >
          cd .. && tar --exclude="*.tar.gz" -czf
          sdk-repository-${{ github.ref_name }}.tar.gz sdk-nrf-testing

      - name: Upload to Artifactory
        env:
          URL: https://eu.files.nordicsemi.com/artifactory/ncs-src-mirror
        run: >
          cd .. && curl -u ${{ secrets.COM_NORDICSEMI_FILES_BURAN_CI }}
          -T sdk-repository-${{ github.ref_name }}.tar.gz
          ${URL}/${{ github.ref_name }}/sdk-nrf-source.tar.gz
