name: Zip and Send
on:
  push:
    branches:
      - zipAndSend

jobs:
  zip-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Checkout sources
        uses: nordicbuilder/action-checkout-west-update@main
        with:
          git-fetch-depth: 0
          path: workspace/nrf
      # - name: Debug
      #   run: |
      #     ls
      #     pwd
      #     cd ..
      #     ls
      - name: Create tar.gz
        run: >
          tar -czf
          sdk-repository-${{ github.ref_name }}.tar.gz workspace/**

      - name: Upload to Artifactory
        env:
          URL: https://eu.files.nordicsemi.com/artifactory/ncs-src-mirror
        run: >
          curl -u ${{ secrets.COM_NORDICSEMI_FILES_BURAN_CI }}
          -T sdk-repository-${{ github.ref_name }}.tar.gz
          ${URL}/${{ github.ref_name }}/sdk-nrf-source.tar.gz
