name: Zip and Send
on:
  push:
    branches:
      - zipAndSend

jobs:
  zip-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Checkout sources
        uses: nordicbuilder/action-checkout-west-update@main
        with:
          git-fetch-depth: 0
          path: nrf
      -name: Debug
       run: |
        ls
        pwd
      # - name: Create tar.gz
      #   run: >
      #     cd .. && tar --exclude="*.tar.gz" -czf
      #     sdk-repository-${{ github.ref_name }}.tar.gz nrf

      # - name: Upload to Artifactory
      #   env:
      #     URL: https://eu.files.nordicsemi.com/artifactory/ncs-src-mirror
      #   run: >
      #     cd .. && curl -u ${{ secrets.COM_NORDICSEMI_FILES_BURAN_CI }}
      #     -T sdk-repository-${{ github.ref_name }}.tar.gz
      #     ${URL}/${{ github.ref_name }}/sdk-nrf-source.tar.gz
