name: Zip and Send
# on:
#   push:
#     tags:
#       - '*'

on:
  push:
    branches:
      - zipAndSend

jobs:
  zip-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          path: sdk-nrf
          fetch-depth: 0
          submodules: 'recursive'

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install West
        run: pip install west

      - name: Initialize West
        run: |
          cd sdk-nrf
          west init -l .

      - name: West update
        run: west update

      - name: Debug
        run: |
          ls
          du -sh ./*
          ls sdk-nrf

      - name: Create tar.gz 
        run: |
          # tar --exclude='.git' --exclude='*.tar.gz' -czf sdk-repository-${{ github.ref_name }}.tar.gz .
          tar -zcf sdk-repository-${{ github.ref_name }}.tar.gz .
      - name: Upload to Artifactory
        run: |
          cd ..
          curl -u ${{ secrets.ARTIFACTORY_BURAN_CI_TOKEN }} -T sdk-repository-${{ github.ref_name }}.tar.gz https://eu.files.nordicsemi.com/artifactory/ncs-src-mirror/${{ github.ref_name }}/sdk-repository-${{ github.ref_name }}.tar.gz
